### ISSUE TITLE
Cant generate working native-image for sample CLI app

### ISSUE THREAD

**Issue by otbe** [micronaut-projects/micronaut-picocli#23]
Hi *,

I would really like to use mn+picocli+native-image for one of our upcoming CLI tools but I cant get it working properly.

Here's an example repo: https://github.com/otbe/micronaut-cli-kotlin-native-image
It was generated by micronaut-cli 1.2.10 by executing `mn create-app org.example.cli --profile cli --lang kotlin --features graal-native-image`. I added the example Command from here https://micronaut-projects.github.io/micronaut-picocli/latest/guide/#generate

I get the following exception while starting the native image:
```
Exception in thread "main" picocli.CommandLine$InitializationException: Could not instantiate class org.example.cli.Application: java.lang.NoSuchMethodException: org.example.cli.Application.<init>
        at picocli.CommandLine$DefaultFactory.create(CommandLine.java:4747)
        at picocli.CommandLine$Model$CommandReflection.getOrCreateInstance(CommandLine.java:9579)
        at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:9522)
        at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:5116)
        at picocli.CommandLine.<init>(CommandLine.java:223)
        at picocli.CommandLine.run(CommandLine.java:2830)
        at picocli.CommandLine.run(CommandLine.java:2755)
        at io.micronaut.configuration.picocli.PicocliRunner.run(PicocliRunner.java:139)
        at io.micronaut.configuration.picocli.PicocliRunner.run(PicocliRunner.java:117)
        at org.example.cli.Application$Companion.main(Application.kt:22)
        at org.example.cli.Application.main(Application.kt)
Caused by: java.lang.NoSuchMethodException: org.example.cli.Application.<init>
        at java.lang.Class.getConstructor0(DynamicHub.java:3082)
        at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2178)
        at picocli.CommandLine$DefaultFactory.create(CommandLine.java:4723)
        at io.micronaut.configuration.picocli.MicronautFactory.create(MicronautFactory.java:74)
        at picocli.CommandLine$DefaultFactory.create(CommandLine.java:4746)
        ... 10 more
```
The app works quite fine when started via java -jar. I also tried to use maven as build tool and Java as language. All combinations lead to the same stacktrace.

Steps to reproduce:
- checkout repo
- `$ ./gradlew build`
- `$ java -jar build/libs/cli-0.1-all.jar -h` -> works
- `$ native-image --no-server -cp  build/libs/cli-0.1-all.jar`
- `$ ./cli` -> fails with the exception above

I also tried building a docker container (using the docker-build.sh) but the result stays the same.

Any ideas whats wrong here?

Thank you very much!

**UPDATE**: I updated the example repo and added @Introspected to the `Application` class (like said on gitter) but that didnt help. Error stays the same

**Comment by valentingoebel** [comment]
Honestly, I have spent quite a lot of time tracking this problem through the picocli and micronaut-picocli codebase and when I realized how trivial the cause was I got a bit angry. In [micronaut-picocli 1.2.0](https://github.com/micronaut-projects/micronaut-picocli/blob/v1.2.0/picocli/src/main/java/io/micronaut/configuration/picocli/MicronautFactory.java#L71) You used to get a NoSuchBeanException but now in version 1.2.1 it is falling back to the DefaultFactory again which is using reflection to instantiate a no argument constructor. This fallback factory simply doesn't work with native-image.

**Comment by graemerocher** [comment]
@valentingoebel would you be able to send a PR?

@remkop Do you know of any changes in Picocli that would cause this? Or is it on the Micronaut side?

**Comment by remkop** [comment]
Sorry for missing this. I wasn't watching this space, I am now.

I disagree with @valentingoebel's analysis, the fallback factory is necessary when the object we're trying to instantiate is not a Micronaut Bean. The fallback factory is picocli's DefaultFactory, which works fine with native-image, but uses reflection, and therefore requires configuration.
This configuration is required anyway, because picocli also uses reflection to set option values in `@Option`-annotated fields etc.

The problem is that the project does not have a `reflect-config.json` configuration that tells GraalVM which fields, methods and constructors will be reflectively accessed. That is why the application works fine when started via java -jar, and fails as a native image.

This configuration can be auto-generated. Picocli has a [`picocli-codegen` module](https://github.com/remkop/picocli/tree/master/picocli-codegen) that generates the necessary configuration. For a java project, the annotation processor in `picocli-codegen` can generate the configuration at compile time. For a java project, all that is necessary is adding this line to your `build.gradle`:

```
annotationProcessor 'info.picocli:picocli-codegen:4.2.0'
```

For a Kotlin project, the Java annotation processor does not work, so you will need to [do a bit more work](https://github.com/remkop/picocli/tree/master/picocli-codegen#gradle-1) in the `build.gradle`:

First, add a custom configuration for the `picocli-codegen` module to your `gradle.build`. This allows us to add this module to the classpath of our custom task without adding it as a dependency to the "standard" build.

```
configurations {
    generateConfig
}
dependencies {
    //...
    generateConfig 'info.picocli:picocli-codegen:4.2.0'
}
```

Then, add a custom task to run the `ReflectionConfigGenerator` tool. This example generates the file during the assemble lifecycle task, there are [alternatives](https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_tasks).

```
task(generateGraalReflectionConfig, dependsOn: 'classes', type: JavaExec) {
    main = 'picocli.codegen.aot.graalvm.ReflectionConfigGenerator'
    classpath = configurations.generateConfig + sourceSets.main.runtimeClasspath
    def outputFile = "${buildDir}/resources/main/META-INF/native-image/${project.group}/${project.name}/reflect-config.json"
    args = ["--output=$outputFile", 'com.your.package.YourCommand1', 'com.your.package.YourCommand2']
}
assemble.dependsOn generateGraalReflectionConfig
```

**Comment by remkop** [comment]
@otbe, @valentingoebel, Please let us know whether the above helped resolve the problem.
I'd be happy to dive in deeper if there's any remaining issue.

**Comment by graemerocher** [comment]
I guess the bigger question for me is why we are generating a non-working application out of the box. Since the `Application` class is not a Micronaut bean it falls back to the reflection business. You could just add `@Singleton` to the `Application` class

**Comment by otbe** [comment]
Thanks for all your responses :)

@graemerocher adding `@Singleton` to the application class didnt help. Exception stays the same.

@remkop adding the codegen configuration finally did the trick. I updated the example repo at https://github.com/otbe/micronaut-cli-kotlin-native-image .

**Comment by remkop** [comment]
@otbe, thanks for confirming!

@graemerocher The factory is not the problem. Picocli is going to use reflection to discover and process the picocli annotations like `@Option`, regardless of whether the Micronaut factory is used or not. So the `reflect-config.json` is needed for native images.

> ... why we are generating a non-working application out of the box. 

Fair point. Strictly speaking, the app does work when started via java -jar, but I get your point, can we do better for native images? Yes, we can. For Java apps, `mn create-app xxx --profile cli` can generate a `build.gradle` that includes this line in the dependencies:

```
annotationProcessor 'info.picocli:picocli-codegen:4.2.0'
```

For Groovy and Kotlin apps, we can auto-generate a `build.gradle` with the additional snippets explained in my previous comment.

**Comment by graemerocher** [comment]
Kotlin apps should work with `kapt 'info.picocli:picocli-codegen:4.2.0'`

**Comment by valentingoebel** [comment]
Yes, the cause of the problem was the missing annotation processor. My first comment is wrong because I just wasn't aware that there was reflection support for graalvm native-image at all so I assumed the fallback was never going to work. When I added the bean it crashed somewhere else and then it became obvious that I needed `picocli-codegen` which isn't mentioned in the  [micronaut-picocli docs](https://micronaut-projects.github.io/micronaut-picocli/latest/guide/)

**Comment by remkop** [comment]
@valentingoebel Yes, the docs have been reorganized a bit and the advice for picocli-specific GraalVM configuration was moved into the GraalVM FAQ: https://docs.micronaut.io/latest/guide/index.html#graalFAQ
It would make sense to duplicate that information in the docs for the micronaut-picocli module.

**Comment by remkop** [comment]
@otbe @valentingoebel Would you mind checking @graemerocher’s suggestion? It sounds you may be able to simplify the `gradle.build` significantly compared to my suggestion.

**Comment by valentingoebel** [comment]
The only line I am adding to `build.gradle` is `annotationProcessor 'info.picocli:picocli-codegen:4.0.3'` in Java projects and `kapt 'info.picocli:picocli-codegen:4.0.3'` in Kotlin projects. I cannot build groovy projects at all for some reason.

**Comment by remkop** [comment]
@valentingoebel I see, thanks for the confirmation. (FYI, I recommend upgrading to picocli 4.2.0 for various [bug fixes and features](https://github.com/remkop/picocli/releases)).

For Groovy, you may need something like the `generateGraalReflectionConfig` custom Gradle task. Unless by “I cannot build groovy projects at all for some reason” you mean there’s a bigger problem than just native images, is that the case?

**Comment by valentingoebel** [comment]
When I use this command to create the project it simply refuses to build.
```
mn create-cli-app --lang=groovy --features=graal-native-image groovycli
cd groovycli
./gradlew assemble
```

```
> Task :compileGroovy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGroovy'.
> Could not resolve all files for configuration ':annotationProcessor'.
   > Could not find io.micronaut.configuration:micronaut-picocli:.
     Required by:
         project :
   > Could not find io.micronaut:micronaut-graal:.
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed

```

I am not sure what the cause is. Are annotation processors supported for groovy?

**Comment by otbe** [comment]
Updated the example repo. Works great with `kapt` thanks @graemerocher @remkop

**Comment by remkop** [comment]
@valentingoebel The generated `build.gradle` for a Groovy project seems to be missing two crucial version numbers in the dependencies. Modifying these 2 lines fixes the issue:

```
dependencies {
    annotationProcessor "io.micronaut.configuration:micronaut-picocli:1.2.1" // add 1.2.1
    annotationProcessor "io.micronaut:micronaut-graal:$micronautVersion" // add $micronautVersion
...
```

**Comment by remkop** [comment]
@otbe, thanks for the confirmation. I will update the [`picocli-codegen` documentation](https://github.com/remkop/picocli/tree/master/picocli-codegen#gradle) to add a section for Kotlin under Enabling the Annotation Processor.

@graemerocher Below I listed some potential action items derived from the discussion above. How would you like to proceed?

* Improve `create-app` templates so that generated `build.xml` for `mn create-app org.example.cli --profile cli --lang kotlin --features graal-native-image` includes `kapt 'info.picocli:picocli-codegen:4.2.0'`. This fixes the "cannot create native image for kotlin app" issue.
* Improve `create-app` templates so that generated `build.xml` for `mn create-cli-app --lang=groovy --features=graal-native-image groovycli` has version numbers for `annotationProcessor "io.micronaut.configuration:micronaut-picocli"` and `annotationProcessor "io.micronaut:micronaut-graal"`. This fixes the "failing build for groovy apps" issue.
* Improve `create-app` templates so that generated `build.xml` for `mn create-cli-app --lang=groovy --features=graal-native-image groovycli` has a custom task to invoke the picocli `picocli.codegen.aot.graalvm.ReflectionConfigGenerator`, as documented [here](generateGraalReflectionConfig). This fixes the "cannot create native image for groovy app" issue, that I assume exists, even though it has not been reported yet.
* Can testing for  `create-app` templates be automated to catch issues where a generated app does not build? This would prevent the failing build issue.
* Documentation for https://docs.micronaut.io/latest/guide/index.html#graalFAQ should also be included in the docs for the micronaut-picocli module (https://micronaut-projects.github.io/micronaut-picocli/latest/guide/). Without this, even diligent users who actually read the docs don't have the information they need.

All, let me know if I missed anything.

**Comment by valentingoebel** [comment]
The version numbers are derived from `micronaut-bom`. The groovy project requires you to specify the BOM multiple times for every single dependency type.

```
annotationProcessor(platform("io.micronaut:micronaut-bom:$micronautVersion")) // doesn't exist, needs to be added
implementation(platform("io.micronaut:micronaut-bom:$micronautVersion")) // already exists
testImplementation platform("io.micronaut:micronaut-bom:$micronautVersion") // already exists
compileOnly platform("io.micronaut:micronaut-bom:$micronautVersion") // already exists
```

**Comment by remkop** [comment]
@valentingoebel If I understand you correctly, you are suggesting to change one line in the BOM rather than 2 lines in the generated `build.gradle`, is that correct?
Are you sure that works though? `micronaut-picocli` has a different version number than `micronaut-graal`...

**Comment by valentingoebel** [comment]
Just take a look at the configured versions: https://mvnrepository.com/artifact/io.micronaut/micronaut-bom/1.3.2 (Ctrl+F `micronaut-picocli`) it points to version 1.2.1.

**Comment by remkop** [comment]
@otbe, @valentingoebel, I updated the picocli docs ([user manual](https://picocli.info/#_annotation_processor) and `picocli-codegen` [README](https://github.com/remkop/picocli/tree/master/picocli-codegen)) to clarify that `kapt` can be used instead of `annotationProcessor` in the build. (Thanks for pointing that out, @graemerocher!)

**Comment by graemerocher** [comment]
Duplicates #28

**Comment by remkop** [comment]
Strictly speaking this ticket does not duplicate #28; #28 is not related to native-image creation.

But I agree this ticket can be closed since a follow-up ticket was created in https://github.com/micronaut-projects/micronaut-profiles/issues/244 and the immediate problem reported by @otbe was addressed by adding the `picocli-codegen` annotation processor to the build.

**Comment by graemerocher** [comment]
btw I am unsure if `picocli-codegen` is strictly needed. We are not using it for https://github.com/micronaut-projects/micronaut-starter/tree/master/starter-cli

**Comment by remkop** [comment]
Please see my discussion with @jameskleeh here: https://github.com/remkop/picocli/issues/1003

**Comment by graemerocher** [comment]
I believe this would be fixed by adding `micronaut-picocli` and `micronaut-graal` to the annotation processor classpath. See https://github.com/micronaut-projects/micronaut-picocli/blob/master/picocli/src/main/java/io/micronaut/configuration/picocli/annotation/PicocliTypeElementVisitor.java

Which visits fields and methods annotated by picocli and ensures they are configured for GraalVM and reflection

**Comment by remkop** [comment]
It is possible that  `micronaut-picocli` and `micronaut-graal` together end up generating the same `reflection-config.json` as  `picocli-codegen`.

I have only tested `picocli-codegen`.

**Comment by remkop** [comment]
@graemerocher, I have some concern about positioning the combination of `micronaut-picocli` and `micronaut-graal` as a replacement for `picocli-codegen`.

The picocli project already provides a solution for building native images, which is `picocli-codegen`. What is the benefit of building a parallel solution that depends on picocli internals? If there is a better way of doing things I am happy to improve the picocli solution, but I am worried that this approach is fragile...

Let me give an example.

Picocli uses reflection not just to deal with the annotations, it also uses reflection to build a jar that can run on Java 5. but at the same time, when run on Java 8, use classes like `java.nio.file.Path`, the `java.time` classes, etc., in its built-in type converters. Currently this reflection on type converter classes is deliberately done in such a way that SubstrateVM can use static analysis to resolve the program elements that are used reflexively. This means that manual configuration with `reflect-config.json` is not necessary, but it also means that these classes are _all_ included in the native image, even if they are not used, unnecessarily adding to the size of the native image file.

One idea to improve picocli in the future is to reduce the size of the native image by only including the types for type converters that are actually used by the application. This means explicitly listing the types that are actually used in the `reflect-config.json` generated by `picocli-codegen`, and changing the reflection logic so that the other types are no longer automatically included by SubstrateVM static analysis. Such a change would work fine for native-image applications that use `picocli-codegen`, but it would potentially break applications that use `micronaut-picocli` and `micronaut-graal` instead.

That is just one example, but this is the concern: **picocli would no longer be free to change the way it uses reflection**, because that might break native-image applications that use `micronaut-picocli` and `micronaut-graal` instead of `picocli-codegen`. Essentially, `micronaut-picocli` and `micronaut-graal` are relying on details of the picocli implementation.

Is the intended usage just internal for the micronaut starter CLI, or are you planning to publish this API also for any user applications that use the micronaut framework?

Again, as I indicated to @jameskleeh in https://github.com/remkop/picocli/issues/1003, I am happy to improve the `picocli-codegen` solution if that is the problem.

Thoughts?

**Comment by graemerocher** [comment]
I agree that it would be better if picocli did this, if `picocli-codegen` can be used as an annotation processor that doesn't require the user to run the app then that is better for sure.

**Comment by remkop** [comment]
It is an annotation processor, so Java and Kotlin apps can just configure it as such.

But it does not have micronaut's nice support for ASTTransformations in Groovy, so Groovy apps need [some configuration](https://github.com/remkop/picocli/tree/master/picocli-codegen#311-generating-reflection-configuration-during-the-build).

**Comment by graemerocher** [comment]
Right, although getting Groovy apps running natively is such a challenge it may not be worth it

**Comment by remkop** [comment]
That is a good point. So, that limitation of `picocli-codegen` is not the problem.

Then what is the advantage of the `micronaut-picocli` / `micronaut-graal` combination over `picocli-codegen`? Is there any other way that `picocli-codegen` should be improved?

**Comment by graemerocher** [comment]
I think we can just use `picocli-codegen` and we should be ok... Using `micronaut-graal` may still be necessary for certain use cases not picocli related

**Comment by remkop** [comment]
Ok, great!

Looking at https://github.com/micronaut-projects/micronaut-picocli/blob/master/picocli/src/main/java/io/micronaut/configuration/picocli/annotation/PicocliTypeElementVisitor.java it seems that it became published API in Micronaut 1.1. 

Should we deprecate it in Micronaut 2.0, to clarify to Micronaut users that they should use `picocli-codegen` instead?

**Comment by graemerocher** [comment]
seems reasonable

**Comment by remkop** [comment]
That is great, thank you. 
What is the next step?
Shall I create a Jira issue in https://github.com/micronaut-projects/micronaut-picocli ?

**Comment by remkop** [comment]
Thinking about this more, can PicocliTypeElementVisitor be removed altogether in Micronaut 2.0?

**Comment by remkop** [comment]
I created https://github.com/micronaut-projects/micronaut-picocli/issues/29
